# pull official base image
## FROM node:alpine
FROM node:15.9.0-alpine3.11 AS builder
LABEL version="1.0"
LABEL description="webpack 5 ts react dev image"
LABEL maintainer = ["geministars@yandex.ru", "artigeministars@gmail.com"]

# set working directory
WORKDIR /opt/web

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
# RUN npm install

# add `/app/node_modules/.bin` to $PATH
ENV PATH="/opt/web/node_modules/.bin:$PATH"
# ENV PATH /app/node_modules/.bin:$PATH
RUN npm install
# --silent
RUN npm audit fix
# add app
COPY . ./

EXPOSE 3000
# start app
CMD ["npm", "run", "dev"]