version: '3.9'

services:

  samplereact:
    container_name: samplereact
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
        - type: bind
          source: .
          target: /app
        - type: volume
           - '/app/node_modules'
    ports:
      - 3005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true