# pull official base image
## FROM node:alpine
FROM node:15.9.0-alpine3.11 AS builder
LABEL version="1.0"
LABEL description="webpac 5 ts react dev image"
LABEL maintainer = ["geministars@yandex.ru", "artigeministars@gmail.com"]

# set working directory
WORKDIR /opt/web

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add `/app/node_modules/.bin` to $PATH
ENV PATH="/opt/web/node_modules/.bin:$PATH"
# ENV PATH /app/node_modules/.bin:$PATH
RUN npm install
# --silent
RUN npm audit fix
# add app
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=builder /opt/web/build /usr/share/nginx/html
# new
COPY ./config/nginx/nginx.dev.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]