version: '3.9'

services:

  samplereactdev:
    container_name: samplewebpackreactdev
    image: samplewebpackreactdev_img
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - type: bind
          source: .
          target: /opt/web
        - '/opt/web/node_modules'
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true